module.exports = {
  INFO: [
    {
      line_number: "004",
      location: "Location D",
      from: "Point G",
      to: "Point H",
      drawing: "Drawing 4",
      service: "Water",
      material: "PVC",
      inservice_date: new Date("2024-01-01T00:00:00Z"),
      pipe_size: 10,
      original_thickness: 0.7,
      stress: 150,
      joint_efficiency: 0.9,
      ca: 160,
      design_life: 50,
      design_pressure: 110,
      operating_pressure: 100,
      design_temperature: 75,
      operating_temperature: 70,
    },
    {
      line_number: "005",
      location: "Location E",
      from: "Point I",
      to: "Point J",
      drawing: "Drawing 5",
      service: "Gas",
      material: "Steel",
      inservice_date: new Date("2024-02-01T00:00:00Z"),
      pipe_size: 12,
      original_thickness: 0.8,
      stress: 160,
      joint_efficiency: 0.95,
      ca: 170,
      design_life: 55,
      design_pressure: 120,
      operating_pressure: 110,
      design_temperature: 80,
      operating_temperature: 75,
    },
  ],
  CML: [
    {
      cml_number: 1,
      cml_description: "CML for Line 004",
      actual_outside_diameter: 10,
      design_thickness: 0.7,
      structural_thickness: 0.6,
      required_thickness: 0.5,
      line_number: "004",
    },
    {
      cml_number: 2,
      cml_description: "CML for Line 005",
      actual_outside_diameter: 12,
      design_thickness: 0.8,
      structural_thickness: 0.7,
      required_thickness: 0.6,
      line_number: "005",
    },
  ],
  TEST_POINT: [
    {
      tp_number: 1,
      tp_description: "Test Point 1 for CML 1",
      note: "Test point 1 for checking thickness",
      id_cml: 118,  
    },
    {
      tp_number: 2,
      tp_description: "Test Point 2 for CML 2",
      note: "Test point 2 for checking thickness",
      id_cml: 119,  
    },
  ],
  THICKNESS: [
    {
      inspection_date: new Date("2024-01-15T00:00:00Z"),
      actual_thickness: 0.5,
      id_tp: 1, 
    },
    {
      inspection_date: new Date("2024-02-10T00:00:00Z"),
      actual_thickness: 0.7,
      id_tp: 2, 
    },
  ],
};
